package mainpackage;

import java.awt.Color;

public class MainJFrame extends javax.swing.JFrame {

    // Creates new form MainJFrame
    public MainJFrame() {
        initComponents();
        getContentPane().setBackground(Color.black);
        setLocationRelativeTo(null);
    }

    // This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        lowerCaseBtn = new javax.swing.JButton();
        upperCaseBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        userInput = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textOutput = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        titleLabel.setFont(new java.awt.Font("Dialog.plain", 1, 48)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Case Converter");

        lowerCaseBtn.setBackground(new java.awt.Color(0, 0, 0));
        lowerCaseBtn.setFont(new java.awt.Font("Dialog.plain", 0, 24)); // NOI18N
        lowerCaseBtn.setForeground(new java.awt.Color(255, 255, 255));
        lowerCaseBtn.setText("Lower Case");
        lowerCaseBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 3));
        lowerCaseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowerCaseBtnActionPerformed(evt);
            }
        });

        upperCaseBtn.setBackground(new java.awt.Color(0, 0, 0));
        upperCaseBtn.setFont(new java.awt.Font("Dialog.plain", 0, 24)); // NOI18N
        upperCaseBtn.setForeground(new java.awt.Color(255, 255, 255));
        upperCaseBtn.setText("Upper Case");
        upperCaseBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 3));
        upperCaseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upperCaseBtnActionPerformed(evt);
            }
        });

        userInput.setBackground(new java.awt.Color(25, 25, 25));
        userInput.setColumns(20);
        userInput.setFont(new java.awt.Font("Dialog.plain", 0, 24)); // NOI18N
        userInput.setForeground(new java.awt.Color(255, 255, 255));
        userInput.setRows(5);
        userInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 3));
        jScrollPane1.setViewportView(userInput);

        textOutput.setEditable(false);
        textOutput.setBackground(new java.awt.Color(25, 25, 25));
        textOutput.setColumns(20);
        textOutput.setFont(new java.awt.Font("Dialog.plain", 0, 24)); // NOI18N
        textOutput.setForeground(new java.awt.Color(255, 255, 255));
        textOutput.setRows(5);
        textOutput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 225), 3));
        jScrollPane2.setViewportView(textOutput);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(397, Short.MAX_VALUE)
                .addComponent(lowerCaseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156)
                .addComponent(upperCaseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(397, 397, 397))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lowerCaseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(upperCaseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    char[] lowerCaseAlphabet = {'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'};
    char[] upperCaseAlphabet = {'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'};
    
    // Lower Case Button
    private void lowerCaseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowerCaseBtnActionPerformed
        // Converts user input into array
        String userInputAsString = userInput.getText();
        char[] userInputAsArray = new char[userInputAsString.length()];
        for (int i = 0; i < userInputAsString.length(); i++) {
            userInputAsArray[i] = userInputAsString.charAt(i);
        }

        // Loop through lenth of alphabet
        for (int i = 0; i < upperCaseAlphabet.length; i++) {
            // Loop through each character of user's text
            for (int u = 0; u < userInputAsArray.length; u++) {
                // Sets upper case characters in user's text to lower case
                if (userInputAsArray[u] == upperCaseAlphabet[i]) {
                    userInputAsArray[u] = lowerCaseAlphabet[i];
                }
            }
        }
        
        String textOutputAsString = new String(userInputAsArray);
        textOutput.setText(textOutputAsString);
    }//GEN-LAST:event_lowerCaseBtnActionPerformed

    // Upper Case Button
    private void upperCaseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upperCaseBtnActionPerformed
        // Converts user input into array
        String userInputAsString = userInput.getText();
        char[] userInputAsArray = new char[userInputAsString.length()];
        for (int i = 0; i < userInputAsString.length(); i++) {
            userInputAsArray[i] = userInputAsString.charAt(i);
        }
        
        // Loop through lenth of alphabet
        for (int i = 0; i < lowerCaseAlphabet.length; i++) {
            // Loop through each character of user's text
            for (int u = 0; u < userInputAsArray.length; u++) {
                // Sets lower case characters in user's text to upper case
                if (userInputAsArray[u] == lowerCaseAlphabet[i]) {
                    userInputAsArray[u] = upperCaseAlphabet[i];
                }
            }
        }
        
        String textOutputAsString = new String(userInputAsArray);
        textOutput.setText(textOutputAsString);
    }//GEN-LAST:event_upperCaseBtnActionPerformed

    public static void main(String args[]) {
        // Set the Nimbus look and feel
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        // Create and display the form
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton lowerCaseBtn;
    private javax.swing.JTextArea textOutput;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton upperCaseBtn;
    private javax.swing.JTextArea userInput;
    // End of variables declaration//GEN-END:variables
}
